### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by BarbaraFl** [systragroup/quetzal#18]
Bonjour,

Lors de l'installation de Quetzal, je n'arrive pas a le faire tourner sur QGis car le message "Cette extension est corrompue Ficher de métadonnées manquant" est affichée.
Quoi faire? C'est un problème de l'installation?

**Comment by qchasserieau** [comment]
Bonjour Quetzal n'est pas une extension QGIS, c'est une librairie python.
Elle doit être installée dans un environnement afin que vous puissiez l'importer dans des scripts python, pas dans Qgis.
Bien à vous,
Quentin
