### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by pe712** [systragroup/quetzal#20]
Bonjour,
J'ai tenté d'installer quetzal. J'ai téléchargé et exécuté miniconda puis j'ai ouvert windows-installer. L'invite de commande fais erreur et donc se ferme avant que je ne puisse lire l'erreur dont il s'agit.

J'ai donc essayé la seconde méthode avec un environnement virtuel. Arrivé à l'étape:Then use python get_conda_install_args.py from the quetzal directory.   J'ai ouvert le fichier avec pyzo (interpretur que j'utilise habituellement) et il me renvoie cette erreur:
Traceback (most recent call last):
  File "C:\Users\bcbav\Downloads\quetzal-master\get_conda_install_args.py", line 6, in <module>
    with open('requirements') as f:
  File "c:\users\bcbav\appdata\local\programs\python\python38\lib\codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'requirements'

Merci pour votre aide

**Comment by qchasserieau** [comment]
Bonjour,
Il y avait une coquille dans windows-install.
J'ai mis à jour la procédure et le readme.

Ce qui marche toujours pour moi (dernière procédure du readme):
j'utilise anaconda prompt pour lancer les commandes.
Je crée l'environnement virtuel manuellement
Je l'active puis je lance windows-install-here via anaconda prompt : si ça plante, au moins on sait pourquoi.

Bon courage

**Comment by pe712** [comment]
Merci pour votre aide,
la dernière procédure a marché. Initiallement ni conda ni python n'avaient
été ajoutés au PATH donc cela ne pouvait pas aboutir

**Comment by qchasserieau** [comment]
@pe712  Thank you for your feedback
