### ISSUE TITLE
Setting up 

### ISSUE THREAD

**Issue by orlandoandradeb** [systragroup/quetzal#34]
Hello ! 
I have been trying to setting up quetzal in my computer for a week. However, it has been complicate for me. Firstly, I think that the modules changed isn't ? 
Because in the example code I see that it wants to import the module  "stepmodel" wich is not  within the modules that I found in the documents. I found the following:

- Analyis 
- Engine 
- Io 
- Model 

Is there going to be a refresh within the documentation, the process for install it and the modules? (for now I have been just available to install it in Mac, in windows I  can not). 

I can contribute with some more code but I will like to have a bit of help for setting up. I have developed a code for data zoning treatment ( what I do is  to modify the data from one zoning to the zoning required ) it is a common problem in transport modeling when you have different zoning. This could enrich the library. 

Thank you.

**Comment by qchasserieau** [comment]
Hi,
We did a refactorization at some point and some modules have changed. However, I think the masters of Quetzal and the examples here
 https://github.com/systragroup/quetzal_paris  are consistent.
If you added the library to your path, the syntax should be from quetzal.model import stepmodel
Or from quetzal.quetzal.model import stepmodel depending on what’s added to your path.

Their will be a refresh in the examples when the dev branch is merged on master in order to keep quetzal_paris and quetzal consistent. The install process is tedious, but it works on windows although some dependencies are sometimes hard to install. You can install the dependencies manually and add the source of Quetzal to your path, it will work because quetzal requires no compilation.

The zoning processing is done in quetzal.syspy.spatial and we’d be glad to have you enrich it.

Kind regards

**Comment by orlandoandradeb** [comment]
Hello @qchasserieau 

Thank you for you answer. Yes I have seen that that modules and submodules have changed. For example in the quetzal_paris in the nootbook A20_GTFS_importer  I can't import the GTFS. The example says the following in the line 5.....

`from quetzal.io.gtfs_reader import importer`
`full_feed = importer.GtfsImporter(path=input_folder + r'/IDFM_gtfs.zip', dist_units='m') `

I can not run the first line becase the function  importer of the submodes gtfs_reader says it is not found:
"AttributeError: module 'quetzal.io.gtfs_reader' has no attribute 'importer' " 



I tryed with other route importing the whole library.... 
`import quetzal`

And then calling directly the function as: 
`full_feed= quetzal.io.gtfs_reader.importer (path=input_folder + r'/IDFM_gtfs.zip', dist_units='m' )`

but this gives me error too with the same argument:  " AttributeError: module 'quetzal.io.gtfs_reader' has no attribute 'importer' " 

What I found most complicarte is the mix of statements from all the sources: 
- The code example says that it has to be use:  `importer.GtfsImporter`. Gtfsimporter  I assume that is a function but  I don't find it within the submodule gtfs_reader , using `help (quetzal.io.gtfs_reader) ` What I found is `importer` that why I tryed to use it in the second way. 

So what is in the example code and what says the library does not match. 

Aditionally, in the online documentation (https://systragroup.github.io/quetzal/docs/build/quetzal.io.gtfs_importer.html)
I don't find any of both what I found is ... 

`class quetzal.io.gtfs_importer.BaseGtfsImporter(gtfs_path)[source]`

I hope you can help me to understand this.  thank you

**Comment by orlandoandradeb** [comment]
Hello @qchasserieau  

I give up with this, I have been trying to use the library for almost 2 weeks and I just can not make it work. I have read the paper you made about the functionalities and it looks great, it has a better performance than other libraries such as  AequilibraE especially because you include public transport,  but because the documentation and process of installing it is hard to use it and make some apports. 

I don't know if you guys which are who truly understand the structure of the library have plans to generate the documeation and make an easy  process of installing available. If the answer is yes I am willing to pay a bit to encourage this process and give me a hand for setting up the library. I am sure that I could contribute making an extra functionality but I have to understand (with documentation) the library.

**Comment by qchasserieau** [comment]
Hi Orlando,
The best way to manage to build your own model with the library is to start from an existing, functional one and change it to match your needs. Indeed, the doc is sometimes scarce or outdated. 

The goal of Quetzal Paris is to provide such functional model. I understand from your post that one notebook of the example (quetzal_paris)is currently not consistent with the master branch of the quetzal. I’ll look into that when I am back from holidays and fix it. However, each notebook have inputs and outputs that are tracked on git, which means that you should be able to run them independently from your issue in the first one. It would grant you access to quetzal’s objects and help you understand the logic behind it. Have you done that, do the other notebooks work ?

**Comment by qchasserieau** [comment]
INSTALLATION

Regarding the install process, windows-install works on most PCs where it creates a virtual env named quetzal_env that we activate to use in notebooks (change kernel)
But it is a wobbly cookbook, i some of the dependencies that are not pip installable on windows update their conda-forge, it can break. As I was writing, quetzal itself require no installation, you can download the source, add them to you path, install the dependencies and it works, this is pretty much what the installer tries to do.

**Comment by qchasserieau** [comment]
CONTACT

I hope that you will manage to make it work without assistance because the aim is to provide a tool that does not need us to be used.

However, Systra’s consultancy can help you build a model.
I also help fellow modelers during my free time if it is not too time consuming.

Anyways I would be glad to hear about you and your project, you can send a email to qchasserieau@systra.com 
I am French

Cheers

**Comment by orlandoandradeb** [comment]
Hello @qchasserieau  
Thank you for your replay.  I sent you a mail. 
I will appreciate  if you can give me a hand with the set up when you come back. It will be a quick help. Have a nice holidays. 

Best regards, 
Orlando

**Comment by qchasserieau** [comment]
@orlandoandradeb 
Hi Orlando,
I am glad you gave Quetzal a chance, and managed to install it ; -)
Thank you for the windows install tutorial that you wrote that will sure help python newcomers !
I share it with them here 
[Instalación de Quetzal.pdf](https://github.com/systragroup/quetzal/files/5892632/Instalacion.de.Quetzal.pdf)
