### ISSUE TITLE
rtree package is only compatible with geopandas up to rtree version 0.9.3

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal#45]
Below: an issue received in a email from @marlinarnz
_The rtree package is only compatible with geopandas up to rtree version 0.9.3. 
Could you include this into the requirements file?_

**Comment by davent9** [comment]
Fixed

**Comment by marlinarnz** [comment]
After installing quetzal in a programming course, we realised that the requirements file still includes an rtree version > 0.9.3, which caused errors for half of the participants. In general, it is better to not specify a version, if not neccessary to let pip/conda some degrees of freedom. However, applying some minor changes, the attached file worked for everyone.
[requirements.txt](https://github.com/systragroup/quetzal/files/6699424/requirements.txt)

**Comment by Ifechukwude94** [comment]
To check if my installation worked properly, I was able to import the 3 checks except for 
==> from quetzal.model import stepmodel

It gives this error : 

==> PyTables is not installed. No support for HDF output.
         SQLalchemy is not installed. No support for SQL output.

==> No module named 'numba'

**Comment by marlinarnz** [comment]
The `numba` package is required in recent versions of quetzal, but it has caused bugs on several machines. I would use an older, more stable, version, which does not require this package, by checking out commit `1126c05c8366e871893b85a55bd57d9d20e7d1d0`

**Comment by siforf564** [comment]
Missing librairies have been added to the requirements in latest commit. Sorry all for this.

Tested on windows with wheels installation (recommended method on windows).
