### ISSUE TITLE
pathfinder engine B needs an od_set

### ISSUE THREAD

**Issue by sfortinsystra** [systragroup/quetzal#61]
The new pathfinder engine (b) needs an od_set. Otherwise, it throw an error. The case where no od_set is set should be handle

**Comment by siforf564** [comment]
Also, broken_modes=True does seems to work:
sm.step_pt_pathfinder(
broken_routes=False,
broken_modes=True,
route_column='route_short_name',
mode_column='route_type',
od_set=od_set
)

Error:
`File ~\Documents\quetzal_paris\notebooks\transport\../../../quetzal\quetzal\engine\pathfinder_utils.py:259, in sparse_matrix(edges, index)    257 nlen = len(index)
    258 coefficients = zip(*((index[u], index[v], w) for u, v, w in edges))
--> 259 row, col, data = coefficients
    260 return csr_matrix((data, (row, col)), shape=(nlen, nlen)), index

ValueError: not enough values to unpack (expected 3, got 0)`
